// Product and Category database curated for Bellissima

export const CATEGORIES = [
  {
    id: 'saree',
    name: 'Sarees',
    slug: 'saree',
    description: 'Exquisite handloomed sarees blending heritage and modern drapes',
    image: '/images/Model Shoot/DSC_0087_first.jpg',
  },
  {
    id: 'handbag',
    name: 'Handbags & Potlis',
    slug: 'handbag',
    description: 'Premium handcrafted clutches, bags, and traditional potlis',
    image: '/images/Purse/DSC_0029.jpg',
  },
  {
    id: 'jewellery',
    name: 'Jewellery',
    slug: 'jewellery',
    description: 'Timeless statement jewellery hand-curated for festive styling',
    image: '/images/Jewelley/DSC_0020.JPG',
  },
  {
    id: 'dress-material',
    name: 'Dress Material',
    slug: 'dress-material',
    description: 'Premium unstitched dress suit fabrics with traditional weaves',
    image: '/images/categories/chanderi.jpg',
  },
];

export const PRODUCTS = [
  // --- MODEL SHOOT SAREES ---
  {
    id: 1,
    name: 'Pure Gadwal Peacock Blue Saree',
    slug: 'pure-gadwal-peacock-blue-saree',
    sku: 'BLM-SAR-092',
    category: 'saree',
    price: 14500,
    description: 'A gorgeous 9-inch border pure Gadwal saree in an exquisite peacock blue and navy blue color combination. Handloomed with premium silk and featuring a heavy zari border and pallu.',
    fabric: 'Pure Gadwal Silk',
    color: 'Peacock Blue & Navy Blue',
    occasion: 'Wedding, Festive, Reception',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean only. Store wrapped in soft muslin.',
    images: [
      '/images/Model Shoot/DSC_0087_first.jpg',
      '/images/Model Shoot/DSC_0079_second.jpg',
      '/images/Model Shoot/DSC_0084_third.jpg',
      '/images/Model Shoot/DSC_0092_fourth.jpg'
    ],
    featured: true,
    newArrival: true,
    stock: 2,
    active: true,
  },
  {
    id: 2,
    name: 'Pure Jamdani Silk Saree',
    slug: 'pure-jamdani-silk-saree',
    sku: 'BLM-SAR-049',
    category: 'saree',
    price: 12800,
    description: 'An elegant pure Jamdani silk saree in beautiful pink, featuring delicate hand-woven floral motifs throughout the body. Exceedingly lightweight with a sophisticated drape.',
    fabric: 'Pure Jamdani Silk',
    color: 'Pink',
    occasion: 'Festive, Party, Reception',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean only.',
    images: [
      '/images/Model Shoot/DSC_0045_first.jpg',
      '/images/Model Shoot/DSC_0049_second.jpg',
      '/images/Model Shoot/DSC_0046_third.jpg',
      '/images/Model Shoot/DSC_0047_fourth.jpg'
    ],
    featured: true,
    newArrival: true,
    stock: 3,
    active: true,
  },
  {
    id: 3,
    name: 'Yellow Semi Silk Saree',
    slug: 'yellow-semi-silk-saree',
    sku: 'BLM-SAR-029',
    category: 'saree',
    price: 4500,
    description: 'A vibrant yellow semi-silk saree with a traditional gold zari border. Comfortable to drape, lightweight, and perfect for haldi, pujas, or daytime celebrations.',
    fabric: 'Semi Silk',
    color: 'Yellow',
    occasion: 'Festival, Puja, Haldi',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean or gentle hand wash.',
    images: [
      '/images/Model Shoot/DSC_0022_first.jpg',
      '/images/Model Shoot/DSC_0025_second.jpg',
      '/images/Model Shoot/DSC_0017_third.jpg',
      '/images/Model Shoot/DSC_0020_fourth.jpg'
    ],
    featured: false,
    newArrival: false,
    stock: 5,
    active: true,
  },
  {
    id: 4,
    name: 'Cotton Silk Maheshwari Saree',
    slug: 'cotton-silk-maheshwari-saree',
    sku: 'BLM-SAR-041',
    category: 'saree',
    price: 6200,
    description: 'A classic Cotton Silk Maheshwari saree in pink with a signature border. Blends the breathability of fine cotton with the natural sheen and elegance of silk.',
    fabric: 'Cotton Silk Maheshwari',
    color: 'Pink',
    occasion: 'Casual Festive, Puja, Office',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean recommended.',
    images: [
      '/images/Model Shoot/DSC_0005_ first.jpg',
      '/images/Model Shoot/DSC_0008_second.jpg',
      '/images/Model Shoot/DSC_0002 _third.jpg',
      '/images/Model Shoot/DSC_0011_fourth.jpg'
    ],
    featured: true,
    newArrival: false,
    stock: 4,
    active: true,
  },

  // --- NEW FOLDER SAREES ---
  {
    id: 5,
    name: 'Elegant Banarasi Saree',
    slug: 'elegant-banarasi-saree-2650',
    sku: 'BLM-SAR-BANARASI-2650',
    category: 'saree',
    price: 2650,
    description: 'A classically woven Banarasi saree featuring a majestic crimson body detailed with traditional golden motifs and an elegant border.',
    fabric: 'Banarasi Silk',
    color: 'Crimson & Gold',
    occasion: 'Festive, Ceremony',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean only.',
    images: [
      '/images/Saree/Banarasi Saree 2650--/DSC_0018 (1).jpg',
      '/images/Saree/Banarasi Saree 2650--/DSC_0019 (1).jpg'
    ],
    featured: true,
    newArrival: true,
    stock: 3,
    active: true,
  },
  {
    id: 6,
    name: 'Banarasi Saree with Butte',
    slug: 'banarasi-saree-with-butte-3050',
    sku: 'BLM-SAR-BAN-BUTTE-3050',
    category: 'saree',
    price: 3050,
    description: 'Beautifully crafted Banarasi saree set apart by its delicate gold butte work spaced gracefully across the rich green fabric and finished with a thick border.',
    fabric: 'Banarasi Silk',
    color: 'Green & Gold',
    occasion: 'Festive, Ceremony',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean recommended.',
    images: [
      '/images/Saree/Banarasi Saree with butte 3050--/DSC_0034 (1).jpg',
      '/images/Saree/Banarasi Saree with butte 3050--/DSC_0035 (1).jpg',
      '/images/Saree/Banarasi Saree with butte 3050--/DSC_0036 (1).jpg'
    ],
    featured: true,
    newArrival: true,
    stock: 4,
    active: true,
  },
  {
    id: 7,
    name: 'Classic Jamdani Saree',
    slug: 'classic-jamdani-saree-1550',
    sku: 'BLM-SAR-JAMDANI-1550',
    category: 'saree',
    price: 1550,
    description: 'A lightweight and breathable Jamdani saree featuring subtle floral hand-weaves. Provides an elegant and airy drape perfect for festivals and casual wear.',
    fabric: 'Jamdani Silk',
    color: 'Off-White & Gold',
    occasion: 'Festive, Casual',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Gentle hand wash in cold water.',
    images: [
      '/images/Saree/Jamdani 1550--/DSC_0025 (1).jpg',
      '/images/Saree/Jamdani 1550--/DSC_0026 (1).jpg',
      '/images/Saree/Jamdani 1550--/DSC_0029 (1).jpg'
    ],
    featured: false,
    newArrival: false,
    stock: 5,
    active: true,
  },
  {
    id: 8,
    name: 'Kanchi Silk Saree',
    slug: 'kanchi-silk-saree-3050',
    sku: 'BLM-SAR-KANCHI-3050',
    category: 'saree',
    price: 3050,
    description: 'A traditional Kanchi Silk Saree displaying rich color depth and handloomed check accents. Perfect choice for auspicious ceremonies and temple wear.',
    fabric: 'Kanchipuram Silk',
    color: 'Royal Purple & Gold',
    occasion: 'Wedding, Festive',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean only. Store wrapped in cotton cloth.',
    images: [
      '/images/Saree/Kanchi Silk 3050--/DSC_0010 (1).jpg',
      '/images/Saree/Kanchi Silk 3050--/DSC_0013 (1).jpg'
    ],
    featured: true,
    newArrival: true,
    stock: 2,
    active: true,
  },
  {
    id: 9,
    name: 'Kantha with Ikat Pallu Saree',
    slug: 'kantha-with-ikat-pallu-saree-3150',
    sku: 'BLM-SAR-KANTHA-IKAT-3150',
    category: 'saree',
    price: 3150,
    description: 'A magnificent combination of detailed Kantha embroidery and a contrasting geometric Ikat woven pallu. Adds an artistic flair to your traditional style.',
    fabric: 'Kantha Cotton Silk',
    color: 'Multicolor Accent',
    occasion: 'Casual, Festive',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean only.',
    images: [
      '/images/Saree/Kantha with ikat pallu 3150--/DSC_0045 (1).jpg',
      '/images/Saree/Kantha with ikat pallu 3150--/DSC_0058 (2) (1).jpg',
      '/images/Saree/Kantha with ikat pallu 3150--/DSC_0060 (2) (1).jpg',
      '/images/Saree/Kantha with ikat pallu 3150--/DSC_0061 (2) (1).jpg',
      '/images/Saree/Kantha with ikat pallu 3150--/DSC_0062 (1) (1).jpg',
      '/images/Saree/Kantha with ikat pallu 3150--/DSC_0063 (1).jpg'
    ],
    featured: false,
    newArrival: true,
    stock: 3,
    active: true,
  },
  {
    id: 10,
    name: 'Kota Silk Saree',
    slug: 'kota-silk-saree-4840',
    sku: 'BLM-SAR-KOTA-4840',
    category: 'saree',
    price: 4840,
    description: 'An elegant and translucent Kota Silk saree displaying classic checkered weave patterns and a subtle golden border that captures natural light beautifully.',
    fabric: 'Kota Silk',
    color: 'Blue & Gold',
    occasion: 'Festive, Puja',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Gentle hand wash. Iron on low heat.',
    images: [
      '/images/Saree/Kota Silk 4840--/DSC_0058 (1).jpg'
    ],
    featured: false,
    newArrival: false,
    stock: 5,
    active: true,
  },
  {
    id: 11,
    name: 'Exquisite Organza Saree',
    slug: 'exquisite-organza-saree-1550',
    sku: 'BLM-SAR-ORGANZA-1550',
    category: 'saree',
    price: 1550,
    description: 'A dreamy, lightweight organza saree detailed with floral patterns and a delicate silver trim. Its sheer fabric makes it elegant for day-to-night styling.',
    fabric: 'Organza',
    color: 'Pink & Silver',
    occasion: 'Party, Festive',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean recommended.',
    images: [
      '/images/Saree/Organza Saree 1550--/DSC_0040 (1).jpg',
      '/images/Saree/Organza Saree 1550--/DSC_0041 (1).jpg',
      '/images/Saree/Organza Saree 1550--/DSC_0042 (1).jpg',
      '/images/Saree/Organza Saree 1550--/DSC_0043 (1).jpg'
    ],
    featured: true,
    newArrival: false,
    stock: 6,
    active: true,
  },
  {
    id: 12,
    name: 'Pure Chanderi Cotton Saree',
    slug: 'pure-chanderi-cotton-saree-4850',
    sku: 'BLM-SAR-CHANDERI-4850',
    category: 'saree',
    price: 4850,
    description: 'A lightweight and breathable Chanderi Cotton Saree in pure ivory. Accented with subtle golden thread borders to bring a clean, dignified look.',
    fabric: 'Chanderi Cotton',
    color: 'Ivory & Gold',
    occasion: 'Puja, Festive',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Hand wash gently. Hang to dry.',
    images: [
      '/images/Saree/Pure Chanderi Cotton 4850--/DSC_0055 (1).jpg'
    ],
    featured: false,
    newArrival: false,
    stock: 4,
    active: true,
  },
  {
    id: 13,
    name: 'Pure Jamdani Silk Saree',
    slug: 'pure-jamdani-silk-saree-folder',
    sku: 'BLM-SAR-PUREJAMDANI',
    category: 'saree',
    price: null, // Price not mentioned, leave blank
    description: 'A luxurious pure Jamdani silk saree of spectacular quality, handwoven with delicate traditional motifs. Elegant drape that feels soft and regal.',
    fabric: 'Pure Jamdani Silk',
    color: 'Magenta',
    occasion: 'Festive, Reception',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean only.',
    images: [
      '/images/Saree/Pure Jamdani Silk Sarees/DSC_0060 (1).jpg'
    ],
    featured: true,
    newArrival: true,
    stock: 2,
    active: true,
  },
  {
    id: 14,
    name: 'Pure Silk Banarasi Kora Saree',
    slug: 'pure-silk-banarasi-kora-saree-13550',
    sku: 'BLM-SAR-KORA-13550',
    category: 'saree',
    price: 13550,
    description: 'An premium handloomed Banarasi Kora silk saree. Extremely fine sheer silk fabric woven with premium zari structures, ideal for brides and receptions.',
    fabric: 'Banarasi Kora Silk',
    color: 'Pastel Peach & Gold',
    occasion: 'Wedding, Reception',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean only. Handle with care.',
    images: [
      '/images/Saree/Pure silk banarasi kora 13550--/DSC_0061 (1).jpg',
      '/images/Saree/Pure silk banarasi kora 13550--/DSC_0065 (1).jpg'
    ],
    featured: true,
    newArrival: true,
    stock: 2,
    active: true,
  },
  {
    id: 15,
    name: 'Semi Raw Silk Saree',
    slug: 'semi-raw-silk-saree-2950',
    sku: 'BLM-SAR-SEMIRAW-2950',
    category: 'saree',
    price: 2950,
    description: 'A semi-raw silk saree with a rustic, textured body and a rich teal pallu. Perfect balance of traditional weaving and modern design.',
    fabric: 'Semi Raw Silk',
    color: 'Mustard & Teal',
    occasion: 'Festive, Puja',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean recommended.',
    images: [
      '/images/Saree/Semi Raw Silk 2950--/DSC_0017 (1).jpg',
      '/images/Saree/Semi Raw Silk 2950--/DSC_0065 (2) (1).jpg',
      '/images/Saree/Semi Raw Silk 2950--/DSC_0065 (2).JPG',
      '/images/Saree/Semi Raw Silk 2950--/DSC_0070 (1).jpg',
      '/images/Saree/Semi Raw Silk 2950--/DSC_0071 (1).jpg'
    ],
    featured: false,
    newArrival: false,
    stock: 4,
    active: true,
  },
  {
    id: 16,
    name: 'Soft Raw Silk Saree',
    slug: 'soft-raw-silk-saree-2950',
    sku: 'BLM-SAR-SOFTRAW-2950',
    category: 'saree',
    price: 2950,
    description: 'An incredibly soft raw silk saree dyed in elegant teal blue. Displays a soft sheen and drapes easily for all-day comfort during family ceremonies.',
    fabric: 'Soft Raw Silk',
    color: 'Teal Blue',
    occasion: 'Festive, Ceremony',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean only.',
    images: [
      '/images/Saree/Soft raw silk 2950--/DSC_0044 (1).jpg',
      '/images/Saree/Soft raw silk 2950--/DSC_0073 (1).jpg',
      '/images/Saree/Soft raw silk 2950--/DSC_0074 (1).jpg',
      '/images/Saree/Soft raw silk 2950--/DSC_0075 (1).jpg'
    ],
    featured: false,
    newArrival: false,
    stock: 6,
    active: true,
  },
  {
    id: 17,
    name: 'Tasar Paithani Saree',
    slug: 'tasar-paithani-saree-6150',
    sku: 'BLM-SAR-TASARPAITHANI-6150',
    category: 'saree',
    price: 6150,
    description: 'A grand Tasar Paithani silk saree featuring the classic handwoven peacock border and a rich golden pallu that shines at weddings.',
    fabric: 'Tasar Paithani Silk',
    color: 'Orange & Green',
    occasion: 'Wedding, Traditional',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean only.',
    images: [
      '/images/Saree/Tasar Paithani 6150--/DSC_0020 (1).jpg',
      '/images/Saree/Tasar Paithani 6150--/DSC_0068 (1).jpg',
      '/images/Saree/Tasar Paithani 6150--/DSC_0069 (1).jpg'
    ],
    featured: true,
    newArrival: false,
    stock: 3,
    active: true,
  },
  {
    id: 18,
    name: 'Tasar Saree with Banarasi Pallu',
    slug: 'tasar-saree-with-banarasi-pallu',
    sku: 'BLM-SAR-TASARBANARASI',
    category: 'saree',
    price: null, // Price not mentioned, leave blank
    description: 'An elegant beige Tasar silk saree decorated with a contrasting maroon Banarasi woven pallu. The ideal combination of two magnificent textures.',
    fabric: 'Tasar Silk',
    color: 'Beige & Maroon',
    occasion: 'Traditional, Festive',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean only.',
    images: [
      '/images/Saree/Tasar saree with banarasi pallu_/DSC_0048 (1).jpg',
      '/images/Saree/Tasar saree with banarasi pallu_/DSC_0049 (1).jpg',
      '/images/Saree/Tasar saree with banarasi pallu_/DSC_0050 (1).jpg',
      '/images/Saree/Tasar saree with banarasi pallu_/DSC_0051 (1).jpg',
      '/images/Saree/Tasar saree with banarasi pallu_/DSC_0052 (1).jpg'
    ],
    featured: false,
    newArrival: true,
    stock: 5,
    active: true,
  },

  // --- HANDBAGS & POTLIS ---
  {
    id: 19,
    name: 'Bridal Bindal Potli',
    slug: 'bridal-bindal-potli',
    sku: 'BLM-HBG-029',
    category: 'handbag',
    price: 2400,
    description: 'A luxurious handcrafted bridal potli bag featuring beautiful gold thread embroidery, dense bead embellishments, and dynamic hanging pearl drawstrings. Available in stunning gold, ivory, and crimson colorways.',
    fabric: 'Silk Velvet & Beads',
    color: 'Gold',
    occasion: 'Bridal, Wedding, Festive',
    length: 'Standard Potli Size',
    careInstructions: 'Spot clean only. Store in protective pouch.',
    images: [
      '/images/Purse/DSC_0029.jpg'
    ],
    featured: true,
    newArrival: true,
    stock: 6,
    active: true,
  },
  {
    id: 20,
    name: 'Indo Western Functional Handbag',
    slug: 'indo-western-functional-handbag',
    sku: 'BLM-HBG-036',
    category: 'handbag',
    price: 3200,
    description: 'A stylish and versatile functional handbag designed for modern wardrobe styling. Reimagines traditional patterns in a contemporary layout.',
    fabric: 'Brocade & Silk',
    color: 'Multicolor Designer',
    occasion: 'Casual, Semi-Formal, Festive',
    length: '10.5" x 7.0" x 3.0"',
    careInstructions: 'Dry clean recommended.',
    images: [
      '/images/Purse/DSC_0030.jpg',
      '/images/Purse/DSC_0031.jpg',
      '/images/Purse/DSC_0033.jpg',
      '/images/Purse/DSC_0034.jpg',
      '/images/Purse/DSC_0038.jpg'
    ],
    featured: false,
    newArrival: true,
    stock: 10,
    active: true,
  },
  {
    id: 21,
    name: 'Elegant Embroidered Velvet Clutch Set',
    slug: 'elegant-embroidered-velvet-clutch-set',
    sku: 'BLM-HBG-041',
    category: 'handbag',
    price: 2800,
    description: 'A gorgeous embroidered velvet clutch set with multi-functional pockets, structured contours, and detachable metallic slings.',
    fabric: 'Velvet',
    color: 'Pink & Crimson',
    occasion: 'Festive, Party, Reception',
    length: '9.5" x 5.5" x 2.0"',
    careInstructions: 'Spot clean only.',
    images: [
      '/images/Purse/DSC_0041.jpg',
      '/images/Purse/DSC_0043.jpg'
    ],
    featured: true,
    newArrival: true,
    stock: 5,
    active: true,
  },

  // --- JEWELLERY ---
  {
    id: 22,
    name: 'Ethnic AD Earrings',
    slug: 'ethnic-ad-earrings',
    sku: 'BLM-JWL-024',
    category: 'jewellery',
    price: 1500,
    description: 'Beautiful handcrafted ethnic earrings detailed with premium American Diamond (AD) stones, giving a brilliant shimmer suitable for all celebratory looks.',
    fabric: 'AD Stones & Gold Plating',
    color: 'Gold & Diamond White',
    occasion: 'Festive, Party, Celebration',
    length: '2.5 inches',
    careInstructions: 'Keep away from perfume, moisture, and store in airtight box.',
    images: ['/images/Jewelley/DSC_0024.JPG'],
    featured: false,
    newArrival: true,
    stock: 8,
    active: true,
  },
  {
    id: 23,
    name: 'Ethnic Jewellery with Beads',
    slug: 'ethnic-jewellery-with-beads',
    sku: 'BLM-JWL-020',
    category: 'jewellery',
    price: 4500,
    description: 'An elegant traditional necklace set decorated with hand-strung colored beads and gold accents, complemented by matching earrings.',
    fabric: 'Colored Beads & Alloy',
    color: 'Red, Green & Gold',
    occasion: 'Festive, Puja, Wedding',
    length: 'Adjustable Dori Fit',
    careInstructions: 'Store in airtight box after cleaning with dry cloth.',
    images: [
      '/images/Jewelley/DSC_0020.JPG',
      '/images/Jewelley/DSC_0022.JPG'
    ],
    featured: true,
    newArrival: true,
    stock: 3,
    active: true,
  },
  {
    id: 24,
    name: 'Elegant Pearl Jewellery Set',
    slug: 'elegant-pearl-jewellery-set',
    sku: 'BLM-JWL-019',
    category: 'jewellery',
    price: 4200,
    description: 'A classic design featuring multiple lines of premium faux pearls connected with a majestic traditional center pendant. Includes matching pearl drop earrings.',
    fabric: 'Premium Pearls & Stones',
    color: 'Pearl White & Gold',
    occasion: 'Festive, Wedding, Reception',
    length: 'Adjustable Thread',
    careInstructions: 'Clean with soft cloth. Avoid spray and water.',
    images: [
      '/images/Jewelley/DSC_0019.JPG',
      '/images/Jewelley/DSC_0018.JPG'
    ],
    featured: true,
    newArrival: false,
    stock: 4,
    active: true,
  },
  {
    id: 25,
    name: 'Beaded Festive Choker Set',
    slug: 'beaded-festive-choker-set',
    sku: 'BLM-JWL-017',
    category: 'jewellery',
    price: 3800,
    description: 'A high-end choker necklace strung with premium beads. Hugs the neck beautifully and features an adjustable cord for a custom fit.',
    fabric: 'Beads & Alloy Gold Plated',
    color: 'Green, Maroon & Gold',
    occasion: 'Festive, Wedding, Ceremony',
    length: 'Adjustable Choker',
    careInstructions: 'Keep dry. Store in cotton wrap.',
    images: ['/images/Jewelley/DSC_0017.JPG'],
    featured: false,
    newArrival: false,
    stock: 5,
    active: true,
  },
  {
    id: 26,
    name: 'Contemporary Indo Western Necklace Set',
    slug: 'contemporary-indo-western-necklace-set',
    sku: 'BLM-JWL-015',
    category: 'jewellery',
    price: 5200,
    description: 'A sleek, modern design that blends traditional techniques with contemporary geometric style. Ideal for fusion and modern ethnic ensembles.',
    fabric: 'Alloy & Semi-precious Stones',
    color: 'Gold & Mint Green',
    occasion: 'Cocktail, Party, Fusion Wear',
    length: 'Adjustable Fit',
    careInstructions: 'Clean with dry microfiber cloth.',
    images: [
      '/images/Jewelley/DSC_0015.JPG',
      '/images/Jewelley/DSC_0016.JPG'
    ],
    featured: true,
    newArrival: true,
    stock: 3,
    active: true,
  },
  {
    id: 27,
    name: 'Ethnic Single Line Gold Chain Necklace',
    slug: 'ethnic-single-line-gold-chain-necklace',
    sku: 'BLM-JWL-014',
    category: 'jewellery',
    price: 1800,
    description: 'A minimalist single line ethnic neckpiece decorated with gold-toned micro beads and traditional motifs. Perfect for daily styling or subtle layers.',
    fabric: 'Gold Plated Brass',
    color: 'Gold',
    occasion: 'Daily Wear, Casual Festive',
    length: '18 inches',
    careInstructions: 'Store in moisture-free box.',
    images: ['/images/Jewelley/DSC_0014.JPG'],
    featured: false,
    newArrival: false,
    stock: 12,
    active: true,
  },
  {
    id: 28,
    name: 'Ethnic 3-Layer Jondhale Pot',
    slug: 'ethnic-3-layer-jondhale-pot',
    sku: 'BLM-JWL-013',
    category: 'jewellery',
    price: 3200,
    description: 'A traditional Maharashtrian 3-layer jondhale pot (जोंधळे पोत) necklace, symbolic of auspicious heritage and detailed with classic gold beads.',
    fabric: 'Traditional Gold Beads & Thread',
    color: 'Gold',
    occasion: 'Puja, Traditional Festivals, Weddings',
    length: 'Adjustable Dori',
    careInstructions: 'Clean with soft cloth. Avoid liquids.',
    images: ['/images/Jewelley/DSC_0013.JPG'],
    featured: true,
    newArrival: false,
    stock: 2,
    active: true,
  },
  {
    id: 29,
    name: 'Contemporary Elegant Jewellery Set',
    slug: 'contemporary-elegant-jewellery-set',
    sku: 'BLM-JWL-012',
    category: 'jewellery',
    price: 4800,
    description: 'A highly sophisticated contemporary jewellery set. Designed with geometric accents, perfect for cocktail drapes, evening wear, and reception gowns.',
    fabric: 'Premium Alloy & Crystal Stones',
    color: 'Silver & Emerald Green',
    occasion: 'Evening Party, Reception, Cocktail',
    length: 'Adjustable Fit',
    careInstructions: 'Clean with dry cotton only.',
    images: [
      '/images/Jewelley/DSC_0012.JPG',
      '/images/Jewelley/DSC_0011.JPG',
      '/images/Jewelley/DSC_0009.JPG',
      '/images/Jewelley/DSC_0008.JPG'
    ],
    featured: false,
    newArrival: true,
    stock: 6,
    active: true,
  },
  {
    id: 30,
    name: 'Precious Stone Jewellery Set',
    slug: 'precious-stone-jewellery-set',
    sku: 'BLM-JWL-010',
    category: 'jewellery',
    price: 6800,
    description: 'A premium designer necklace set embedded with select semi-precious stone drops and detailed metal carvings. Complemented with heavy earrings.',
    fabric: 'Semi-precious Stones & Gold Finish',
    color: 'Ruby Red & Antique Gold',
    occasion: 'Wedding, Festive, Reception',
    length: 'Adjustable',
    careInstructions: 'Do not expose to chemical cleaners.',
    images: ['/images/Jewelley/DSC_0010.JPG'],
    featured: true,
    newArrival: false,
    stock: 2,
    active: true,
  },
  {
    id: 31,
    name: 'Ethnic AD Necklace Set',
    slug: 'ethnic-ad-necklace-set',
    sku: 'BLM-JWL-007',
    category: 'jewellery',
    price: 5400,
    description: 'A stunning traditional necklace set studded with premium American Diamond (AD) stones. Designed to provide a brilliant and clean diamond look.',
    fabric: 'American Diamond & Alloy',
    color: 'Sparkling White & Gold',
    occasion: 'Wedding, Festive, Reception',
    length: 'Adjustable Neck Size',
    careInstructions: 'Keep in airtight jewelry cover.',
    images: [
      '/images/Jewelley/DSC_0007.JPG',
      '/images/Jewelley/DSC_0003.JPG'
    ],
    featured: false,
    newArrival: false,
    stock: 4,
    active: true,
  },
  {
    id: 32,
    name: 'AD Necklace with Pearl Drops',
    slug: 'ad-necklace-with-pearl-drops',
    sku: 'BLM-JWL-006',
    category: 'jewellery',
    price: 4900,
    description: 'A beautiful blend of sparkling American Diamond (AD) stone clusters and elegant hanging pearl drops, ideal for modern festivity styling.',
    fabric: 'AD & Premium Pearls',
    color: 'Gold, White & Pearl',
    occasion: 'Festive, Party, Reception',
    length: 'Adjustable Dori',
    careInstructions: 'Avoid sweat, chemicals, and water.',
    images: ['/images/Jewelley/DSC_0006.JPG'],
    featured: false,
    newArrival: true,
    stock: 7,
    active: true,
  },
  {
    id: 33,
    name: 'Ethnic Antique Gold Necklace Set',
    slug: 'ethnic-antique-gold-necklace-set',
    sku: 'BLM-JWL-005',
    category: 'jewellery',
    price: 3600,
    description: 'A classic antique-finish necklace set with detailed temple carving designs and small golden beads. Timeless styling piece for festive drapes.',
    fabric: 'Gold Plated Brass Alloy',
    color: 'Antique Gold',
    occasion: 'Puja, Festive, Traditional Wear',
    length: 'Adjustable Dori',
    careInstructions: 'Clean with dry cloth only.',
    images: ['/images/Jewelley/DSC_0005.JPG'],
    featured: false,
    newArrival: false,
    stock: 10,
    active: true,
  },
  {
    id: 34,
    name: 'Fashion Necklace Set with AD',
    slug: 'fashion-necklace-set-with-ad',
    sku: 'BLM-JWL-004',
    category: 'jewellery',
    price: 3400,
    description: 'An elegant fashion necklace set with sparkling American Diamond settings, offering a sleek, sophisticated visual appeal at parties.',
    fabric: 'AD Stones & Silver Plating',
    color: 'Silver & Diamond White',
    occasion: 'Party, Cocktail, Festive',
    length: 'Adjustable Fit',
    careInstructions: 'Store in plastic airtight pouch.',
    images: ['/images/Jewelley/DSC_0004.JPG'],
    featured: false,
    newArrival: false,
    stock: 5,
    active: true,
  },
  {
    id: 35,
    name: 'Ethnic AD into Western Fusion Necklace Set',
    slug: 'ethnic-ad-into-western-fusion-necklace-set',
    sku: 'BLM-JWL-0001',
    category: 'jewellery',
    price: 5600,
    description: 'A striking fusion necklace set that pairs traditional AD work with modern Western silhouettes, designed for statements at receptions.',
    fabric: 'Premium AD & Rhodium Plating',
    color: 'Sparkling Silver & Emerald Green',
    occasion: 'Reception, Evening Gown, Party',
    length: 'Adjustable Neckline',
    careInstructions: 'Wipe clean after use and keep dry.',
    images: ['/images/Jewelley/DSC_0001.JPG'],
    featured: true,
    newArrival: true,
    stock: 3,
    active: true,
  },

  // --- DRESS MATERIALS ---
  {
    id: 36,
    name: 'Banarasi Katan Silk Suit Set',
    slug: 'banarasi-katan-silk-suit-set',
    sku: 'BLM-DSM-001',
    category: 'dress-material',
    price: 9500,
    description: 'A premium unstitched 3-piece salwar suit material set. Features a rich handloomed Katan silk top with all-over zari butas, plain silk bottom fabric, and a heavy woven Banarasi dupatta.',
    fabric: 'Katan Silk',
    color: 'Deep Teal & Royal Blue',
    occasion: 'Festive, Puja, Reception',
    length: 'Top: 2.5m, Bottom: 2.5m, Dupatta: 2.3m',
    careInstructions: 'Dry clean only.',
    images: ['/images/products/dress-1-b.jpg'],
    featured: true,
    newArrival: true,
    stock: 5,
    active: true,
  },
  {
    id: 37,
    name: 'Indigo Hand-Block Cotton Suit Set',
    slug: 'indigo-hand-block-cotton-suit-set',
    sku: 'BLM-DSM-002',
    category: 'dress-material',
    price: 3400,
    description: 'Comfortable unstitched pure cotton dress fabric set, featuring authentic Ajrakh indigo hand-block prints. Comes with a block-printed bottom fabric and a lightweight cotton mulmul printed dupatta.',
    fabric: 'Organic Cotton',
    color: 'Indigo Blue & Madder Red',
    occasion: 'Casual Wear, Office wear',
    length: 'Top: 2.5m, Bottom: 2.5m, Dupatta: 2.5m',
    careInstructions: 'Wash separately in cold water with mild detergent. Line dry in shade.',
    images: ['/images/products/dress-2-b.jpg'],
    featured: false,
    newArrival: false,
    stock: 20,
    active: true,
  },
];

export const WHATSAPP_NUMBER = 'XXXXXXX';

export function getWhatsAppUrl(product) {
  const message = `Hi Bellissima! I would like to buy *${product.name}* (SKU: ${product.sku}) from Bellissima. Could you please let me know how to proceed?`;
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
}

export function getRestockWhatsAppUrl(product) {
  const message = `Hi Bellissima! I noticed *${product.name}* (SKU: ${product.sku}) is currently out of stock on Bellissima. Could you let me know when it will be available again? I am very interested!`;
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
}

export function formatPrice(price) {
  if (!price) return '';
  return `₹${price.toLocaleString('en-IN')}`;
}

export function getStockStatus(stock) {
  if (stock === 0) return { label: 'Out of Stock', color: 'text-gray-400', bg: 'bg-gray-100', dot: 'bg-gray-400' };
  if (stock <= 5) return { label: `Only ${stock} left`, color: 'text-amber-600', bg: 'bg-amber-50', dot: 'bg-amber-500' };
  return { label: 'In Stock', color: 'text-emerald-600', bg: 'bg-emerald-50', dot: 'bg-emerald-500' };
}
