// Demo product data — will be replaced with database data in Phase 2

export const CATEGORIES = [
  {
    id: 'saree',
    name: 'Sarees',
    slug: 'saree',
    description: 'Exquisite handloomed sarees blending heritage and modern drapes',
    image: '/images/categories/silk.jpg',
  },
  {
    id: 'handbag',
    name: 'Handbags',
    slug: 'handbag',
    description: 'Premium handcrafted handbags that complement your elegance',
    image: '/images/categories/handbag.jpg',
  },
  {
    id: 'jewellery',
    name: 'Jewellery',
    slug: 'jewellery',
    description: 'Timeless statement jewellery hand-curated for festive styling',
    image: '/images/categories/jewellery.jpg',
  },
  {
    id: 'dress-material',
    name: 'Dress Material',
    slug: 'dress-material',
    description: 'Premium unstitched dress suit fabrics with traditional weaves',
    image: '/images/categories/chanderi.jpg',
  },
];

export const PRODUCTS = [
  // --- SAREES ---
  {
    id: 1,
    name: 'Royal Burgundy Silk Saree',
    slug: 'royal-burgundy-silk-saree',
    sku: 'BLM-SLK-001',
    category: 'saree',
    price: 12500,
    description: 'A stunning pure silk saree in deep burgundy with intricate gold zari border and pallu. The rich texture and lustrous sheen make it perfect for weddings and festive occasions. Handcrafted with traditional weaving techniques passed down through generations.',
    fabric: 'Pure Silk',
    color: 'Burgundy',
    occasion: 'Wedding, Festival',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean only. Store in muslin cloth.',
    images: ['/images/products/silk-1.jpg', '/images/products/silk-1-b.jpg'],
    featured: true,
    newArrival: false,
    stock: 8,
    active: true,
  },
  {
    id: 2,
    name: 'Emerald Banarasi Brocade Saree',
    slug: 'emerald-banarasi-brocade-saree',
    sku: 'BLM-BNR-001',
    category: 'saree',
    price: 18500,
    description: 'Exquisite handwoven Banarasi brocade saree in emerald green with gold and silver zari motifs. The rich Mughal-inspired patterns and heavy pallu make this a showstopper for grand celebrations.',
    fabric: 'Banarasi Silk Brocade',
    color: 'Emerald Green',
    occasion: 'Wedding, Reception',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean only. Do not wring.',
    images: ['/images/products/banarasi-1.jpg', '/images/products/banarasi-1-b.jpg'],
    featured: true,
    newArrival: true,
    stock: 4,
    active: true,
  },
  {
    id: 3,
    name: 'Blush Pink Georgette Saree',
    slug: 'blush-pink-georgette-saree',
    sku: 'BLM-GRG-001',
    category: 'saree',
    price: 5800,
    description: 'A delicate blush pink georgette saree with sequin and thread work along the border. Lightweight and flowy, it drapes beautifully for cocktail parties and evening events.',
    fabric: 'Pure Georgette',
    color: 'Blush Pink',
    occasion: 'Party, Cocktail',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Gentle hand wash or dry clean.',
    images: ['/images/products/georgette-1.jpg', '/images/products/georgette-1-b.jpg'],
    featured: true,
    newArrival: false,
    stock: 12,
    active: true,
  },
  {
    id: 4,
    name: 'Ivory Gold Chanderi Saree',
    slug: 'ivory-gold-chanderi-saree',
    sku: 'BLM-CHN-001',
    category: 'saree',
    price: 7200,
    description: 'A graceful ivory Chanderi saree with delicate gold butis and a sheer texture that catches light beautifully. The traditional Chanderi weave brings a timeless charm.',
    fabric: 'Chanderi Silk Cotton',
    color: 'Ivory & Gold',
    occasion: 'Pooja, Casual Festive',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Gentle hand wash. Iron on low heat.',
    images: ['/images/products/chanderi-1.jpg', '/images/products/chanderi-1-b.jpg'],
    featured: true,
    newArrival: true,
    stock: 6,
    active: true,
  },
  {
    id: 5,
    name: 'Ocean Blue Linen Saree',
    slug: 'ocean-blue-linen-saree',
    sku: 'BLM-LNN-001',
    category: 'saree',
    price: 3800,
    description: 'A breezy ocean blue linen saree with a contrasting coral border. Perfect for daytime events, office wear, or brunch gatherings. Incredibly comfortable and easy to drape.',
    fabric: 'Pure Linen',
    color: 'Ocean Blue',
    occasion: 'Casual, Office, Brunch',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Machine wash gentle cycle. Iron while damp.',
    images: ['/images/products/linen-1.jpg', '/images/products/linen-1-b.jpg'],
    featured: false,
    newArrival: true,
    stock: 15,
    active: true,
  },
  {
    id: 6,
    name: 'Midnight Chiffon Dream Saree',
    slug: 'midnight-chiffon-dream-saree',
    sku: 'BLM-CHF-001',
    category: 'saree',
    price: 4500,
    description: 'A dreamy midnight blue chiffon saree with scattered silver mukaish work that shimmers with every movement. The lightweight fabric makes it ideal for evening soirées.',
    fabric: 'Pure Chiffon',
    color: 'Midnight Blue',
    occasion: 'Evening, Party',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean recommended.',
    images: ['/images/products/chiffon-1.jpg', '/images/products/chiffon-1-b.jpg'],
    featured: true,
    newArrival: false,
    stock: 0,
    active: true,
  },
  {
    id: 7,
    name: 'Marigold Banarasi Silk Saree',
    slug: 'marigold-banarasi-silk-saree',
    sku: 'BLM-BNR-002',
    category: 'saree',
    price: 22000,
    description: 'A magnificent marigold yellow Banarasi silk saree with all-over jaal work in gold zari. The heavy pallu features a traditional kadhwa weave that showcases master craftsmanship.',
    fabric: 'Pure Banarasi Silk',
    color: 'Marigold Yellow',
    occasion: 'Wedding, Haldi',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Dry clean only. Store wrapped in muslin.',
    images: ['/images/products/banarasi-2.jpg', '/images/products/banarasi-2-b.jpg'],
    featured: false,
    newArrival: true,
    stock: 3,
    active: true,
  },
  {
    id: 8,
    name: 'Sage Green Linen Saree',
    slug: 'sage-green-linen-saree',
    sku: 'BLM-LNN-002',
    category: 'saree',
    price: 4200,
    description: 'A serene sage green linen saree with minimalist silver zari border. The earthy tone and natural fabric make this perfect for conscious fashion lovers who value sustainability.',
    fabric: 'Organic Linen',
    color: 'Sage Green',
    occasion: 'Casual, Office',
    length: '6.3 meters (with blouse piece)',
    careInstructions: 'Machine wash cold. Air dry.',
    images: ['/images/products/linen-2.jpg', '/images/products/linen-2-b.jpg'],
    featured: true,
    newArrival: false,
    stock: 10,
    active: true,
  },

  // --- HANDBAGS ---
  {
    id: 9,
    name: 'Royal Velvet Zardosi Potli',
    slug: 'royal-velvet-zardosi-potli',
    sku: 'BLM-HBG-001',
    category: 'handbag',
    price: 3200,
    description: 'A luxurious handcrafted dark burgundy velvet potli bag with detailed golden zardosi embroidery and hanging pearl tassels. Fits perfectly for festive celebrations and wedding wear.',
    fabric: 'Velvet',
    color: 'Burgundy & Gold',
    occasion: 'Festive, Wedding',
    length: 'Standard Potli Size',
    careInstructions: 'Spot clean only. Store in protective wrap.',
    images: ['/images/products/handbag-1.jpg', '/images/products/handbag-1-b.jpg'],
    featured: true,
    newArrival: true,
    stock: 7,
    active: true,
  },
  {
    id: 10,
    name: 'Gilded Brocade Silk Clutch',
    slug: 'gilded-brocade-silk-clutch',
    sku: 'BLM-HBG-002',
    category: 'handbag',
    price: 2800,
    description: 'A sleek rectangular envelope clutch made of pure Banarasi silk brocade, featuring a metallic gold clasp and a detachable chain strap. Perfect combination of traditional weaves and modern utility.',
    fabric: 'Banarasi Brocade Silk',
    color: 'Emerald & Gold',
    occasion: 'Party, Evening, Wedding',
    length: '9.5" x 5.5" x 2.0"',
    careInstructions: 'Dry clean only.',
    images: ['/images/products/handbag-2.jpg', '/images/products/handbag-2-b.jpg'],
    featured: false,
    newArrival: true,
    stock: 12,
    active: true,
  },

  // --- JEWELLERY ---
  {
    id: 11,
    name: 'Kundan Choker & Earring Set',
    slug: 'kundan-choker-earring-set',
    sku: 'BLM-JWL-001',
    category: 'jewellery',
    price: 8500,
    description: 'An elegant handcrafted gold-plated choker set adorned with premium Kundan stones, emerald beads, and tiny drop pearls. Complemented with matching hanging earrings. Features an adjustable cord thread.',
    fabric: 'Kundan',
    color: 'Gold, Emerald & Pearl White',
    occasion: 'Festive, Wedding',
    length: 'Adjustable Choker Fit',
    careInstructions: 'Avoid contact with perfume. Clean with dry cotton cloth after use.',
    images: ['/images/products/jewellery-1.jpg', '/images/products/jewellery-1-b.jpg'],
    featured: true,
    newArrival: true,
    stock: 3,
    active: true,
  },
  {
    id: 12,
    name: 'Antique Gold Plated Jhumkas',
    slug: 'antique-gold-plated-jhumkas',
    sku: 'BLM-JWL-002',
    category: 'jewellery',
    price: 1800,
    description: 'Classic temple jewellery-inspired jhumkas with antique gold finish, featuring detailed embossing work and micro-pearl hanging drops. An absolute necessity for standard ethnic styling.',
    fabric: 'Gold Plated Brass Alloy',
    color: 'Antique Gold',
    occasion: 'Festive, Puja, Ceremony',
    length: '2.5 inches length',
    careInstructions: 'Store in airtight pouch. Keep away from water and sweat.',
    images: ['/images/products/jewellery-2.jpg', '/images/products/jewellery-2-b.jpg'],
    featured: false,
    newArrival: false,
    stock: 15,
    active: true,
  },

  // --- DRESS MATERIALS ---
  {
    id: 13,
    name: 'Banarasi Katan Silk Suit Set',
    slug: 'banarasi-katan-silk-suit-set',
    sku: 'BLM-DSM-001',
    category: 'dress-material',
    price: 9500,
    description: 'A premium unstitched 3-piece salwar suit material set. Features a rich handloomed Katan silk top with all-over zari butas, plain silk bottom fabric, and a heavy woven Banarasi dupatta.',
    fabric: 'Katan Silk',
    color: 'Deep Teal & Royal Blue',
    occasion: 'Festive, Puja, Reception',
    length: 'Top: 2.5m, Bottom: 2.5m, Dupatta: 2.3m',
    careInstructions: 'Dry clean only.',
    images: ['/images/products/dress-1.jpg', '/images/products/dress-1-b.jpg'],
    featured: true,
    newArrival: true,
    stock: 5,
    active: true,
  },
  {
    id: 14,
    name: 'Indigo Hand-Block Cotton Suit Set',
    slug: 'indigo-hand-block-cotton-suit-set',
    sku: 'BLM-DSM-002',
    category: 'dress-material',
    price: 3400,
    description: 'Comfortable unstitched pure cotton dress fabric set, featuring authentic Ajrakh indigo hand-block prints. Comes with a block-printed bottom fabric and a lightweight cotton mulmul printed dupatta.',
    fabric: 'Organic Cotton',
    color: 'Indigo Blue & Madder Red',
    occasion: 'Casual Wear, Office wear',
    length: 'Top: 2.5m, Bottom: 2.5m, Dupatta: 2.5m',
    careInstructions: 'Wash separately in cold water with mild detergent. Line dry in shade.',
    images: ['/images/products/dress-2.jpg', '/images/products/dress-2-b.jpg'],
    featured: false,
    newArrival: false,
    stock: 20,
    active: true,
  },
];

export const WHATSAPP_NUMBER = 'XXXXXXX';

export function getWhatsAppUrl(product) {
  const message = `Hi Bellissimaa! I would like to buy *${product.name}* (SKU: ${product.sku}) from Bellissimaa. Could you please let me know how to proceed?`;
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
}

export function getRestockWhatsAppUrl(product) {
  const message = `Hi Bellissimaa! I noticed *${product.name}* (SKU: ${product.sku}) is currently out of stock on Bellissimaa. Could you let me know when it will be available again? I am very interested!`;
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
}

export function formatPrice(price) {
  return '#';
}

export function getStockStatus(stock) {
  if (stock === 0) return { label: 'Out of Stock', color: 'text-gray-400', bg: 'bg-gray-100', dot: 'bg-gray-400' };
  if (stock <= 5) return { label: `Only ${stock} left`, color: 'text-amber-600', bg: 'bg-amber-50', dot: 'bg-amber-500' };
  return { label: 'In Stock', color: 'text-emerald-600', bg: 'bg-emerald-50', dot: 'bg-emerald-500' };
}
